name: Build nFPM packages
description: Build linux packages using nFPM
inputs:
  packager:
    description: Target package types, deb, rpm, etc.
    required: false
    default: deb
    type: string
  config:
    description: Path to nFPM config file
    type: string
  target:
    description: Where to save generated package
    type: string
    default: dist
  fallback-version:
    description: Version to fall back to if no tag can be found
    type: string
  checkout:
    description: Whether to perform action/checkout
    default: true
  setup-nfpm:
    description: Whether to set up nfpm
    default: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      if: ${{ fromJSON(inputs.checkout) }}
      with:
        fetch-depth: 0 # Required for github-action-get-previous-tag

    - uses: secondlife/setup-nfpm@v2
      if: ${{ fromJSON(inputs.setup-nfpm) }}

    - uses: secondlife-3p/github-action-get-previous-tag@v1
      id: previous-tag
      with:
        fallback: ${{ inputs.fallback-version }}

    - name: Determine next version
      id: version
      shell: bash
      env:
        PREV: ${{ steps.previous-tag.outputs.tag }}
      run: |
        if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
          tag_version="${GITHUB_REF#refs/tags/v}"
        else
          # Add an abbreviated commit to the version to indicate this is a
          # "prerelease" of the previous tag... which really it isn't, it's a
          # prerelease of the next release. If the identified previous tag
          # already has a prerelease portion (`-` in a semantic version), this
          # *will* get two prerelease sections, but that's OK.
          tag_version="${PREV#v}~$(git rev-parse --short HEAD)"
        fi
        # The git tag is a semantic version, where `-` indicates a prerelease
        # version. Debian & RPM packages use `~` to indicate prerelease
        # versions. So translate `-`s into `~`s.
        tag_version="${tag_version//-/\~}"
        echo "value=$tag_version" >> $GITHUB_OUTPUT

    - name: Build deb
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.value }}
        TARGET: ${{ inputs.target }}
        CONFIG: ${{ inputs.config }}
        PACKAGER: ${{ inputs.packager }}
      run: |
        if [[ ! -z "$TARGET" ]]; then
          mkdir -p "$TARGET"
        fi
        nfpm package \
          ${CONFIG:+--config "$CONFIG"} \
          ${TARGET:+--target "$TARGET"} \
          --packager $PACKAGER
